#!/usr/bin/env bash
# Digs a domain and its subdomains
declare -a sdomains=(
[0]="www"
[1]="lb-01"
[2]="web-01"
[3]="web-02"
)

dig_domain () {
    echo -n "The subdomain $1 is a "
}

if [ $# -eq 1 ]; then
    for domain in "${sdomains[@]}"
    do
        dig_domain $domain
        dig +noall +answer "$domain"."$1" | awk '{print $4" record and points to " $5}'
    done
else
    dig_domain $2
    dig +noall +answer "$2"."$1" | awk '{print $4" record and points to " $5}'
    
fi
