#!/usr/bin/env bash
# Install lovley nginx and change it's root defult webpage
apt-get update -y && apt-get install -y nginx
ufw allow 'Nginx HTTP'
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx.debian.bkp
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
