#!/usr/bin/env bash
# Install lovley nginx and change it's root
apt-get update -y && apt-get install -y nginx
sudo systemctl enable nginx
sudo ufw allow 'Nginx HTTP'
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx.debian.bkp
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
