#!/usr/bin/env bash
# Install and config HAporxy
apt-get update -y
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get install haproxy=2.0.\*
echo -e "
frontend http
        bind *:80
        use_backend hbnb
backend hbnb
        balance roundrobin
        server web-01 204.236.240.39:80 check
        server web-02 18.210.19.134:80 check" > /etc/haproxy/haproxy.cfg
service haproxy start
