#!/usr/bin/env bash
# This script prints "Best School" 10 times and "Hello" on 9

CONT=0

while [ $CONT -lt 10 ]; do
    echo "Best School"
    
    if [ $CONT -eq 8 ]; then
        echo "Hello"
    fi

    CONT=$((CONT + 1))
done
