#!/usr/bin/env bash
# This script iterat 10 times
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

CONT=1

while [ $CONT -le 20 ]; do

    echo $CONT

    case $CONT in
        4)
        echo "bad luck from China"
        ;;
        9)
        echo "bad luck from Japan"
        ;;
        17)
        echo "bad luck from Italy"
        ;;
    esac
 
    CONT=$((CONT + 1))
done
