#!/usr/bin/env bash
# Block mark's beloved website form my machine then change my localhost address
cp /etc/hosts ~/hosts_new
echo "127.0.0.2	localhost" > ~/hosts_new
echo "8.8.8.8	facebook.com" >> ~/hosts_new
cp -f ~/hosts_new /etc/hosts
