#!/usr/bin/env bash
# run nginx server as nginx user to prevent attackers from have high privileges
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80 default/8080 default/" /etc/nginx/sites-available/default
sudo -u nginx   service nginx start

